### ISSUE TITLE
Why generic?

### ISSUE THREAD

**Issue by frederikhors** [howtocodeit/hexarch#3]
Can I ask you why are you using:

```rust
struct AppState<BS: BlogService> {
    author_service: Arc<BS>,
}
```

instead of for example a simpler:

```rust
struct AppState {
    author_service: Arc<BlogService>,
}
```

**Comment by TmLev** [comment]
Did you mean
```rust
struct AppState {
    author_service: Arc<dyn BlogService>,
}
```
?

**Comment by frederikhors** [comment]
Yeah, sorry, the question is why generic? To avoid dynamic dispatch?

**Comment by TmLev** [comment]
I think it was answered here: https://github.com/howtocodeit/comments/discussions/5#discussioncomment-9936143.
